### ISSUE TITLE
Google Collab error

### ISSUE THREAD

**Issue by adbmdp** [shobhit9618/celeb_recognition#2]
Hello,
I have a hard time trying to make the Google Colab works.

`encoder_model = torch.load(vggface_modelpath)`

Give this error:
```
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-6-f7e8409fb9ee>](https://localhost:8080/#) in <cell line: 1>()
----> 1 encoder_model = torch.load(vggface_modelpath)
      2 ann_index = AnnoyIndex(2048, 'angular')
      3 _ = ann_index.load(celeb_index_annpath)

2 frames
[/usr/local/lib/python3.10/dist-packages/torch/serialization.py](https://localhost:8080/#) in __init__(self, name, mode)
    424 class _open_file(_opener):
    425     def __init__(self, name, mode):
--> 426         super().__init__(open(name, mode))
    427 
    428     def __exit__(self, *args):

FileNotFoundError: [Errno 2] No such file or directory: 'celeb_detector/models/vggface_resnet50.pt'
```

I can't find this file anywhere on the the repo. I need to download it somewhere?

Thanks!

**Comment by shobhit9618** [comment]
Thanks for trying out the repo. 
I have uploaded the model files to my huggingface repo: https://huggingface.co/resnet151/celeb_detector.

You can install everything using the following commands:
```
git lfs install
git clone https://huggingface.co/resnet151/celeb_detector
cd celeb_detector
pip install -e .
```

You should be able to use the colab notebook after that by pointing to the correct model path.

Best way to run this would be in python by directly importing the package:
```
import cv2
import celeb_detector
out = celeb_detector.get_celebrity(cv2.imread("/path/to/image"))
```

I will be updating the readme soon.

**Comment by shobhit9618** [comment]
There are 117 celebs, I just used a scraping script to download the images, you can easily scale this to many more celebs. The json file has names of all the celebrities.

For training your own model, you can try to follow the readme, might give you some issues here and there, as that script has not been tested for different scenarios, but the code is pretty straightforward, you should be able to debug that.

Regarding the huggingface space, if the model does not detect any celebrity, it just returns back the same image. Check the json file to see the list of supported celebrities.

If you still faces any issue, feel free to ping here.

**Comment by shobhit9618** [comment]
The confidence value is not scaled to 1.0 actually, a good threshold would be 0.2.

For training, anything more than 20 pictures works well. On CPU it would be very slow, you can use a colab GPU itself to train this. 

Just fyi, the model is not getting trained in the traditional sense. The script creates embeddings for the celeb faces and saves those in a vector space (using annoy library), and mappings are stored in a json file.
During inference, we find the embedding for the celeb to be detected, and compare it with the vector space to find the closest match.

**Comment by shobhit9618** [comment]
I just found a bug in the create_celeb_model.py file, can you take  the latest pull and try again? Or you can just copy the latest code from the file and try.

Regarding the face_recognition issue, did you run this command?
`pip install git+https://github.com/ageitgey/face_recognition_models`

If not, please run this once and check.

**Comment by shobhit9618** [comment]
hey thanks for the PR, I have merged it, feel free to use or modify the code for your application.
